language: ruby
rvm:
- 2.5.3
before_script:
- cp config/database.yml.ci config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  run: rake db:migrate
  app: team-avengers
    api_key:
      secure: "Replace me! Let's test Travis CI"
  on:
    repo: netguru-code-college/krk-18-avengers
